BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20 # pixels per cell


WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE


COLOR_BACKGROUND = "#00b33c"
COLOR_BACKGROUND_NIGHT = "#003300"

COLOR_LINE = "#00b33c"


FLAG_ROWS = 3
FLAG_COLS = 4


FLAG_ROW = BOARD_ROWS - FLAG_ROWS
FLAG_COL = BOARD_COLS - FLAG_COLS